export interface DishDetail {
  ingredients: string[];
  macros: { calories: number; protein: number; carbs: number; fat: number };
  allergens?: string[];
}

export const DISH_DETAILS: Record<string, DishDetail> = {
  // ── listing-1: West African Weekend Feast ─────────────────────────────────
  "dish-1-1": {
    ingredients: [
      "Parboiled long-grain rice",
      "Plum tomatoes",
      "Red bell peppers",
      "Scotch bonnet pepper",
      "White onion",
      "Tomato paste",
      "Chicken stock",
      "Groundnut oil",
      "Bay leaves",
      "Thyme",
      "Curry powder",
      "Salt",
    ],
    macros: { calories: 480, protein: 12, carbs: 68, fat: 18 },
    allergens: ["Tree nuts"],
  },
  "dish-1-2": {
    ingredients: [
      "Ground melon seeds (egusi)",
      "Palm oil",
      "Pumpkin leaves (ugwu)",
      "Beef",
      "Dried stockfish",
      "Ground crayfish",
      "White onion",
      "Scotch bonnet pepper",
      "Yam (for fufu)",
      "Seasoning cubes",
      "Salt",
    ],
    macros: { calories: 720, protein: 45, carbs: 52, fat: 38 },
    allergens: ["Fish"],
  },
  "dish-1-3": {
    ingredients: [
      "Beef sirloin",
      "Groundnut powder",
      "Ginger powder",
      "Paprika",
      "Cayenne pepper",
      "Onion powder",
      "Garlic powder",
      "Vegetable oil",
      "Salt",
    ],
    macros: { calories: 380, protein: 42, carbs: 4, fat: 22 },
    allergens: ["Peanuts"],
  },

  // ── listing-2: Korean Banchan Box ─────────────────────────────────────────
  "dish-2-1": {
    ingredients: [
      "Napa cabbage kimchi",
      "Spinach (sigeumchi namul)",
      "Soybean sprouts (kongnamul)",
      "Glass noodles (japchae)",
      "Egg (gyeran-mari)",
      "Gochugaru",
      "Sesame oil",
      "Garlic",
      "Ginger",
      "Soy sauce",
      "Fish sauce",
      "Rice vinegar",
    ],
    macros: { calories: 280, protein: 10, carbs: 42, fat: 8 },
    allergens: ["Eggs", "Fish", "Soy"],
  },
  "dish-2-2": {
    ingredients: [
      "Beef short ribs",
      "Soy sauce",
      "Sesame oil",
      "Garlic",
      "Ginger",
      "Asian pear",
      "Brown sugar",
      "Mirin",
      "Sake",
      "Green onion",
      "Sesame seeds",
    ],
    macros: { calories: 640, protein: 48, carbs: 18, fat: 42 },
    allergens: ["Soy", "Sesame"],
  },
  "dish-2-3": {
    ingredients: [
      "Doenjang (fermented soybean paste)",
      "Firm tofu",
      "Shiitake mushrooms",
      "Zucchini",
      "Potato",
      "White onion",
      "Garlic",
      "Anchovy stock",
      "Gochugaru",
      "Green onion",
    ],
    macros: { calories: 220, protein: 16, carbs: 22, fat: 8 },
    allergens: ["Soy", "Fish"],
  },

  // ── listing-3: Levantine Mezze Spread ─────────────────────────────────────
  "dish-3-1": {
    ingredients: [
      "Chickpeas",
      "Tahini",
      "Lemon juice",
      "Garlic",
      "Eggplant",
      "Extra-virgin olive oil",
      "Flat-leaf parsley",
      "Tomato",
      "Cucumber",
      "Bulgur wheat",
      "Fresh mint",
      "Warm pita bread",
    ],
    macros: { calories: 520, protein: 18, carbs: 64, fat: 22 },
    allergens: ["Gluten", "Sesame"],
  },
  "dish-3-2": {
    ingredients: [
      "Chicken thighs (bone-in)",
      "White onion",
      "Ground sumac",
      "Extra-virgin olive oil",
      "Taboon flatbread",
      "Pine nuts",
      "Allspice",
      "Cinnamon",
      "Cumin",
      "Black pepper",
      "Salt",
    ],
    macros: { calories: 680, protein: 52, carbs: 48, fat: 28 },
    allergens: ["Gluten", "Tree nuts"],
  },
  "dish-3-3": {
    ingredients: [
      "Grape leaves",
      "Short-grain rice",
      "Flat-leaf parsley",
      "Fresh mint",
      "Plum tomato",
      "White onion",
      "Lemon juice",
      "Extra-virgin olive oil",
      "Allspice",
      "Cinnamon",
      "Salt",
      "Black pepper",
    ],
    macros: { calories: 240, protein: 6, carbs: 38, fat: 8 },
    allergens: [],
  },

  // ── listing-4: Brazilian Saturday ─────────────────────────────────────────
  "dish-4-1": {
    ingredients: [
      "Black beans",
      "Pork ribs",
      "Beef chuck",
      "Smoked linguiça sausage",
      "Bacon",
      "White onion",
      "Garlic",
      "Bay leaves",
      "Orange peel",
      "Basmati rice",
      "Farofa (toasted cassava flour)",
      "Salt",
      "Black pepper",
    ],
    macros: { calories: 780, protein: 56, carbs: 62, fat: 32 },
    allergens: [],
  },
  "dish-4-2": {
    ingredients: [
      "Chicken breast",
      "Cream cheese",
      "Catupiry cheese",
      "Wheat flour",
      "Chicken stock",
      "White onion",
      "Garlic",
      "Parsley",
      "Breadcrumbs",
      "Egg",
      "Vegetable oil",
      "Salt",
    ],
    macros: { calories: 480, protein: 28, carbs: 44, fat: 22 },
    allergens: ["Gluten", "Eggs", "Dairy"],
  },
  "dish-4-3": {
    ingredients: [
      "Sweetened condensed milk",
      "Cocoa powder",
      "Unsalted butter",
      "Chocolate sprinkles",
      "Salt",
    ],
    macros: { calories: 380, protein: 6, carbs: 52, fat: 18 },
    allergens: ["Dairy"],
  },

  // ── listing-5: Sunday Italian Meal Prep ──────────────────────────────────
  "dish-5-1": {
    ingredients: [
      "00 flour",
      "Free-range eggs",
      "Ground beef (80/20)",
      "Pork mince",
      "San Marzano tomatoes",
      "Carrot",
      "Celery",
      "White onion",
      "Dry red wine",
      "Whole milk",
      "Extra-virgin olive oil",
      "Bay leaf",
      "Freshly grated nutmeg",
      "Parmigiano Reggiano",
    ],
    macros: { calories: 720, protein: 38, carbs: 68, fat: 28 },
    allergens: ["Gluten", "Eggs", "Dairy"],
  },
  "dish-5-2": {
    ingredients: [
      "Carnaroli rice",
      "Saffron threads",
      "Parmigiano Reggiano",
      "Dry white wine",
      "White onion",
      "Unsalted butter",
      "Homemade chicken stock",
      "Salt",
      "White pepper",
    ],
    macros: { calories: 540, protein: 18, carbs: 72, fat: 22 },
    allergens: ["Dairy"],
  },
  "dish-5-3": {
    ingredients: [
      "Savoiardi ladyfingers",
      "Mascarpone",
      "Free-range eggs",
      "Caster sugar",
      "Espresso",
      "Amaretto",
      "Unsweetened cocoa powder",
      "Salt",
    ],
    macros: { calories: 420, protein: 10, carbs: 38, fat: 26 },
    allergens: ["Gluten", "Eggs", "Dairy"],
  },

  // ── listing-6: Suya Express ───────────────────────────────────────────────
  "dish-6-1": {
    ingredients: [
      "Beef sirloin",
      "Groundnut powder",
      "Ginger powder",
      "Paprika",
      "Cayenne pepper",
      "Onion powder",
      "Garlic powder",
      "Vegetable oil",
      "Salt",
    ],
    macros: { calories: 380, protein: 42, carbs: 4, fat: 22 },
    allergens: ["Peanuts"],
  },
  "dish-6-2": {
    ingredients: [
      "Beef suya strips",
      "Flatbread",
      "Red bell pepper",
      "White onion",
      "Plum tomato",
      "Yaji spice blend",
      "Vegetable oil",
      "Salt",
    ],
    macros: { calories: 520, protein: 38, carbs: 42, fat: 18 },
    allergens: ["Gluten", "Peanuts"],
  },

  // ── listing-7: K-BBQ Box ──────────────────────────────────────────────────
  "dish-7-1": {
    ingredients: [
      "Beef rib eye (bulgogi cut)",
      "Beef short ribs (galbi)",
      "Pork belly (samgyeopsal)",
      "Chicken thigh (dak galbi)",
      "Soy sauce",
      "Sesame oil",
      "Garlic",
      "Ginger",
      "Asian pear",
      "Gochujang",
      "Green onion",
      "Sesame seeds",
    ],
    macros: { calories: 1200, protein: 96, carbs: 28, fat: 78 },
    allergens: ["Soy", "Sesame"],
  },
  "dish-7-2": {
    ingredients: [
      "Napa cabbage kimchi",
      "Spinach namul",
      "Bean sprout namul",
      "Pickled radish",
      "Spicy cucumber",
      "Gochugaru",
      "Sesame oil",
      "Garlic",
      "Soy sauce",
      "Fish sauce",
    ],
    macros: { calories: 240, protein: 8, carbs: 36, fat: 6 },
    allergens: ["Fish", "Soy", "Sesame"],
  },

  // ── listing-8: Halal Weekly Prep Box ─────────────────────────────────────
  "dish-8-1": {
    ingredients: [
      "Chicken thighs",
      "Garlic",
      "Lemon juice",
      "Ground cumin",
      "Smoked paprika",
      "Turmeric",
      "Ground coriander",
      "Plain yogurt",
      "Extra-virgin olive oil",
      "Salt",
      "Fresh parsley",
    ],
    macros: { calories: 420, protein: 48, carbs: 8, fat: 22 },
    allergens: ["Dairy"],
  },
  "dish-8-2": {
    ingredients: [
      "Romaine lettuce",
      "Plum tomato",
      "Cucumber",
      "Radish",
      "Ground sumac",
      "Pita chips",
      "Chickpeas",
      "Tahini",
      "Lemon juice",
      "Garlic",
      "Extra-virgin olive oil",
      "Flat-leaf parsley",
      "Pomegranate seeds",
      "Warm pita bread",
    ],
    macros: { calories: 380, protein: 14, carbs: 48, fat: 16 },
    allergens: ["Gluten", "Sesame"],
  },

  // ── listing-9: Priya's Thali Weekly ──────────────────────────────────────
  "dish-9-1": {
    ingredients: [
      "Red lentils (dal tadka)",
      "Potato",
      "Cauliflower",
      "Atta wheat flour",
      "Basmati rice",
      "Full-fat yogurt",
      "Ghee",
      "Cumin seeds",
      "Mustard seeds",
      "Turmeric",
      "Coriander powder",
      "Garam masala",
      "Fresh coriander",
      "Milk-based mithai",
    ],
    macros: { calories: 680, protein: 22, carbs: 92, fat: 18 },
    allergens: ["Gluten", "Dairy"],
  },
  "dish-9-2": {
    ingredients: [
      "Chicken thighs",
      "Butter",
      "Heavy cream",
      "San Marzano tomatoes",
      "Cashews",
      "Red lentils",
      "Basmati rice",
      "Atta wheat flour",
      "Plain yogurt",
      "Ghee",
      "Garam masala",
      "Turmeric",
      "Fresh ginger",
      "Garlic",
      "Dried fenugreek leaves",
    ],
    macros: { calories: 820, protein: 52, carbs: 78, fat: 28 },
    allergens: ["Gluten", "Dairy", "Tree nuts"],
  },

  // ── listing-10: Biryani Friday ────────────────────────────────────────────
  "dish-10-1": {
    ingredients: [
      "Bone-in chicken",
      "Aged basmati rice",
      "Crispy fried onions",
      "Saffron-infused milk",
      "Ghee",
      "Green cardamom",
      "Cloves",
      "Cinnamon stick",
      "Star anise",
      "Bay leaf",
      "Plain yogurt",
      "Fresh ginger",
      "Garlic",
      "Fresh mint",
      "Fresh coriander",
      "Biryani masala",
    ],
    macros: { calories: 780, protein: 48, carbs: 82, fat: 26 },
    allergens: ["Dairy"],
  },
  "dish-10-2": {
    ingredients: [
      "Aged basmati rice",
      "Seasonal mixed vegetables",
      "Cashews",
      "Golden raisins",
      "Saffron threads",
      "Ghee",
      "Whole spices",
      "Plain yogurt",
      "Fresh ginger",
      "Garlic",
      "Fresh mint",
      "Fresh coriander",
      "Rose water",
    ],
    macros: { calories: 620, protein: 16, carbs: 96, fat: 20 },
    allergens: ["Dairy", "Tree nuts"],
  },

  // ── listing-11: Tonkotsu Ramen Kit ───────────────────────────────────────
  "dish-11-1": {
    ingredients: [
      "Pork trotters",
      "Pork neck bones",
      "Chashu pork belly",
      "Sun-dried ramen noodles",
      "Soft-boiled marinated eggs",
      "Bamboo shoots (menma)",
      "Nori",
      "Sweet corn",
      "Green onion",
      "Sesame seeds",
      "Tare sauce (soy, mirin, sake)",
      "Mayu black garlic oil",
      "Salt",
    ],
    macros: { calories: 820, protein: 52, carbs: 68, fat: 38 },
    allergens: ["Gluten", "Eggs", "Soy", "Sesame"],
  },
  "dish-11-2": {
    ingredients: [
      "Chicken carcasses",
      "Chicken chashu",
      "Sun-dried ramen noodles",
      "Bamboo shoots",
      "Soft-boiled egg",
      "Nori",
      "Green onion",
      "Soy tare",
      "Mirin",
      "Sake",
      "Kombu dashi",
      "Sesame oil",
    ],
    macros: { calories: 680, protein: 46, carbs: 72, fat: 22 },
    allergens: ["Gluten", "Eggs", "Soy", "Sesame", "Fish"],
  },

  // ── listing-12: Bento Lunch Box ───────────────────────────────────────────
  "dish-12-1": {
    ingredients: [
      "Atlantic salmon fillet",
      "Teriyaki sauce (soy sauce, mirin, sake, sugar)",
      "Sushi rice",
      "Rice vinegar",
      "Tamagoyaki (eggs, dashi, mirin, sugar)",
      "Persian cucumber",
      "Edamame",
      "Black sesame seeds",
      "Toasted nori",
    ],
    macros: { calories: 580, protein: 38, carbs: 62, fat: 18 },
    allergens: ["Fish", "Eggs", "Soy", "Sesame"],
  },
  "dish-12-2": {
    ingredients: [
      "Chicken thigh",
      "Soy sauce",
      "Sake",
      "Fresh ginger",
      "Garlic",
      "Potato starch",
      "Vegetable oil",
      "Sushi rice",
      "Japanese mayo",
      "Napa cabbage",
      "Pickled ginger",
      "Sesame seeds",
    ],
    macros: { calories: 640, protein: 42, carbs: 58, fat: 26 },
    allergens: ["Gluten", "Eggs", "Soy", "Sesame"],
  },

  // ── listing-13: Jerk Chicken Box ─────────────────────────────────────────
  "dish-13-1": {
    ingredients: [
      "Chicken half (bone-in)",
      "Scotch bonnet peppers",
      "Whole allspice (pimento)",
      "Fresh thyme",
      "Garlic",
      "Fresh ginger",
      "Green onion",
      "Cinnamon",
      "Nutmeg",
      "Brown sugar",
      "Soy sauce",
      "Vegetable oil",
      "Long-grain rice",
      "Red kidney beans",
      "Coconut milk",
      "Cabbage",
    ],
    macros: { calories: 680, protein: 58, carbs: 52, fat: 22 },
    allergens: ["Soy"],
  },
  "dish-13-2": {
    ingredients: [
      "Whole chicken",
      "Scotch bonnet peppers",
      "Whole allspice",
      "Fresh thyme",
      "Garlic",
      "Fresh ginger",
      "Green onion",
      "Cinnamon",
      "Nutmeg",
      "Brown sugar",
      "Soy sauce",
      "Vegetable oil",
      "Long-grain rice",
      "Red kidney beans",
      "Coconut milk",
      "Cabbage",
      "Festival dumplings",
    ],
    macros: { calories: 1360, protein: 116, carbs: 104, fat: 44 },
    allergens: ["Gluten", "Soy"],
  },

  // ── listing-14: Caribbean Stew Weekly ────────────────────────────────────
  "dish-14-1": {
    ingredients: [
      "Goat shoulder (bone-in)",
      "Scotch bonnet pepper",
      "Jamaican curry powder",
      "Fresh thyme",
      "Whole allspice",
      "Garlic",
      "Fresh ginger",
      "White onion",
      "Potato",
      "Coconut milk",
      "Long-grain rice",
      "Red kidney beans",
      "Salt",
      "Black pepper",
    ],
    macros: { calories: 720, protein: 52, carbs: 58, fat: 28 },
    allergens: [],
  },
  "dish-14-2": {
    ingredients: [
      "Oxtail",
      "Butter beans",
      "White onion",
      "Garlic",
      "Fresh ginger",
      "Scotch bonnet pepper",
      "Fresh thyme",
      "Whole allspice",
      "Brown sugar",
      "Soy sauce",
      "Tomato paste",
      "Worcestershire sauce",
      "Salt",
    ],
    macros: { calories: 860, protein: 62, carbs: 42, fat: 48 },
    allergens: ["Soy"],
  },

  // ── listing-15: Pasta Alla Norma ──────────────────────────────────────────
  "dish-15-1": {
    ingredients: [
      "Rigatoni pasta",
      "Sicilian eggplant",
      "San Marzano tomatoes",
      "Ricotta salata",
      "Garlic",
      "Extra-virgin olive oil",
      "Fresh basil",
      "Dried chili flakes",
      "Salt",
      "Black pepper",
    ],
    macros: { calories: 580, protein: 18, carbs: 82, fat: 18 },
    allergens: ["Gluten", "Dairy"],
  },
  "dish-15-2": {
    ingredients: [
      "Arborio risotto",
      "Saffron threads",
      "Fior di latte mozzarella",
      "Breadcrumbs",
      "Free-range eggs",
      "Parmigiano Reggiano",
      "Vegetable oil",
      "Dry white wine",
      "Unsalted butter",
      "White onion",
      "Salt",
    ],
    macros: { calories: 480, protein: 16, carbs: 54, fat: 24 },
    allergens: ["Gluten", "Eggs", "Dairy"],
  },
};
